// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// **************************************************************************
// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import,unnecessary_import,unused_shown_name,implementation_imports,duplicate_import
/// The routeNames auto generated by https://github.com/fluttercandies/ff_annotation_route
const List<String> routeNames = <String>[
  '/index',
  '/moreComment',
  '/subjectDetail',
  '/subjectEp',
];

/// The routes auto generated by https://github.com/fluttercandies/ff_annotation_route
class Routes {
  const Routes._();

  /// '/index'
  ///
  /// [name] : '/index'
  static const String index = '/index';

  /// '/moreComment'
  ///
  /// [name] : '/moreComment'
  ///
  /// [constructors] :
  ///
  /// MoreCommentsPage : [int(required) subjectID]
  static const String moreComment = '/moreComment';

  /// '/subjectDetail'
  ///
  /// [name] : '/subjectDetail'
  ///
  /// [constructors] :
  ///
  /// BangumiDetailPage : [int(required) bangumiID]
  static const String subjectDetail = '/subjectDetail';

  /// '/subjectEp'
  ///
  /// [name] : '/subjectEp'
  ///
  /// [constructors] :
  ///
  /// BangumiEpPage : [int(required) subjectID, int? epIndex]
  static const String subjectEp = '/subjectEp';
}
