// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// version: 10.1.0
// **************************************************************************
// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import,unnecessary_import,unused_shown_name,implementation_imports,duplicate_import,library_private_types_in_public_api
/// The routeNames auto generated by https://github.com/fluttercandies/ff_annotation_route
const List<String> routeNames = <String>[
  '/Blog',
  '/Groups',
  '/Timeline',
  '/TimelineChat',
  '/commentPreview',
  '/groupTopic',
  '/history',
  '/index',
  '/loginAuth',
  '/moreReviews',
  '/moreTopics',
  '/notificationsPage',
  '/photoView',
  '/sendComment',
  '/subjectComment',
  '/subjectDetail',
  '/subjectEp',
  '/subjectTopic',
  '/webview',
  'about',
  'settings',
  'userPage',
];

/// The routes auto generated by https://github.com/fluttercandies/ff_annotation_route
class Routes {
  const Routes._();

  /// '/Blog'
  ///
  /// [name] : '/Blog'
  ///
  /// [constructors] :
  ///
  /// BangumiBlogPage : [ReviewModel(required) reviewModel, ReviewInfo(required) reviewInfo, Color? themeColor, int? referPostContentID, String? sourceTitle]
  static const String blog = '/Blog';

  /// '/Groups'
  ///
  /// [name] : '/Groups'
  ///
  /// [constructors] :
  ///
  /// BangumiGroupsPage : [GroupInfo? selectedGroupInfo]
  static const String groups = '/Groups';

  /// '/Timeline'
  ///
  /// [name] : '/Timeline'
  static const String timeline = '/Timeline';

  /// '/TimelineChat'
  ///
  /// [name] : '/TimelineChat'
  ///
  /// [constructors] :
  ///
  /// BangumiTimelineChatPage : [int(required) timelineID, String? comment,  Function(int)? onDeleteAction, String? userName, int? createdAt]
  static const String timelineChat = '/TimelineChat';

  /// '/commentPreview'
  ///
  /// [name] : '/commentPreview'
  ///
  /// [constructors] :
  ///
  /// SendCommentPreview : [String(required) renderText]
  static const String commentPreview = '/commentPreview';

  /// '/groupTopic'
  ///
  /// [name] : '/groupTopic'
  ///
  /// [constructors] :
  ///
  /// BangumiGroupTopicPage : [GroupsModel(required) groupsModel, GroupTopicInfo(required) groupTopicInfo, Color? themeColor, int? referPostContentID]
  static const String groupTopic = '/groupTopic';

  /// '/history'
  ///
  /// [name] : '/history'
  static const String history = '/history';

  /// '/index'
  ///
  /// [name] : '/index'
  static const String index = '/index';

  /// '/loginAuth'
  ///
  /// [name] : '/loginAuth'
  static const String loginAuth = '/loginAuth';

  /// '/moreReviews'
  ///
  /// [name] : '/moreReviews'
  ///
  /// [constructors] :
  ///
  /// MoreReviewsPage : [ReviewModel(required) reviewModel, Color? bangumiThemeColor, String? title]
  static const String moreReviews = '/moreReviews';

  /// '/moreTopics'
  ///
  /// [name] : '/moreTopics'
  ///
  /// [constructors] :
  ///
  /// MoreTopicsPage : [TopicModel(required) topicModel, Color? bangumiThemeColor, String? title]
  static const String moreTopics = '/moreTopics';

  /// '/notificationsPage'
  ///
  /// [name] : '/notificationsPage'
  static const String notificationsPage = '/notificationsPage';

  /// '/photoView'
  ///
  /// [name] : '/photoView'
  ///
  /// [constructors] :
  ///
  /// BangumiPictureViewPage : [ImageProvider(required) imageProvider, String? name]
  static const String photoView = '/photoView';

  /// '/sendComment'
  ///
  /// [name] : '/sendComment'
  ///
  /// [constructors] :
  ///
  /// SendCommentPage : [dynamic contentID, int? replyID, String? title, PostCommentType? postCommentType, UserContentActionType? actionType, String? referenceObject,  Function(String)? onSendMessage, (String, String)? preservationContent, Color? themeColor]
  static const String sendComment = '/sendComment';

  /// '/subjectComment'
  ///
  /// [name] : '/subjectComment'
  ///
  /// [constructors] :
  ///
  /// BangumiCommentPage : [CommentModel(required) commentModel, int(required) subjectID, Color? bangumiThemeColor, String? name]
  static const String subjectComment = '/subjectComment';

  /// '/subjectDetail'
  ///
  /// [name] : '/subjectDetail'
  ///
  /// [constructors] :
  ///
  /// BangumiDetailPage : [int(required) subjectID]
  static const String subjectDetail = '/subjectDetail';

  /// '/subjectEp'
  ///
  /// [name] : '/subjectEp'
  ///
  /// [constructors] :
  ///
  /// BangumiEpPage : [EpModel(required) epModel, Color? bangumiThemeColor, int? referPostContentID]
  static const String subjectEp = '/subjectEp';

  /// '/subjectTopic'
  ///
  /// [name] : '/subjectTopic'
  ///
  /// [constructors] :
  ///
  /// BangumiTopicPage : [TopicModel(required) topicModel, TopicInfo(required) topicInfo, Color? themeColor, int? referPostContentID, String? sourceTitle]
  static const String subjectTopic = '/subjectTopic';

  /// '/webview'
  ///
  /// [name] : '/webview'
  ///
  /// [constructors] :
  ///
  /// BangumiWebviewPage : [String(required) url, String? title, String? injectHTML,  Function(String?)? onTargetUrlReached]
  static const String webview = '/webview';

  /// 'about'
  ///
  /// [name] : 'about'
  static const String about = 'about';

  /// 'settings'
  ///
  /// [name] : 'settings'
  static const String settings = 'settings';

  /// 'userPage'
  ///
  /// [name] : 'userPage'
  static const String userPage = 'userPage';
}
