// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// version: 10.1.0
// **************************************************************************
// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import,unnecessary_import,unused_shown_name,implementation_imports,duplicate_import,library_private_types_in_public_api
import 'package:bangu_lite/internal/const.dart';
import 'package:bangu_lite/models/providers/comment_model.dart';
import 'package:bangu_lite/models/providers/ep_model.dart';
import 'package:bangu_lite/models/providers/review_model.dart';
import 'package:bangu_lite/models/providers/topic_model.dart';
import 'package:bangu_lite/models/review_details.dart';
import 'package:bangu_lite/models/topic_info.dart';
import 'package:ff_annotation_route_library/ff_annotation_route_library.dart';
import 'package:flutter/widgets.dart';

import '../catalogs/about_page.dart';
import '../catalogs/bangumi_blog_page.dart';
import '../catalogs/bangumi_comment_page.dart';
import '../catalogs/bangumi_comment_preview.dart';
import '../catalogs/bangumi_detail_page.dart';
import '../catalogs/bangumi_ep_page.dart';
import '../catalogs/bangumi_index_page.dart';
import '../catalogs/bangumi_picture_view_page.dart';
import '../catalogs/bangumi_topic_page.dart';
import '../catalogs/bangumi_webview_page.dart';
import '../catalogs/banumi_user_page.dart';
import '../catalogs/more_reviews_page.dart';
import '../catalogs/more_topics_page.dart';
import '../catalogs/send_comment_page.dart';
import '../catalogs/settings_page.dart';

/// Get route settings base on route name, auto generated by https://github.com/fluttercandies/ff_annotation_route
FFRouteSettings getRouteSettings({
  required String name,
  Map<String, dynamic>? arguments,
  PageBuilder? notFoundPageBuilder,
}) {
  final Map<String, dynamic> safeArguments =
      arguments ?? const <String, dynamic>{};
  switch (name) {
    case '/Blog':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => BangumiBlogPage(
          key: asT<Key?>(
            safeArguments['key'],
          ),
          reviewModel: asT<ReviewModel>(
            safeArguments['reviewModel'],
          )!,
          selectedBlogIndex: asT<int>(
            safeArguments['selectedBlogIndex'],
          )!,
          themeColor: asT<Color?>(
            safeArguments['themeColor'],
          ),
        ),
      );
    case '/commentPreview':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => BangumiCommentPreview(
          key: asT<Key?>(
            safeArguments['key'],
          ),
          renderText: asT<String>(
            safeArguments['renderText'],
          )!,
        ),
      );
    case '/index':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => BangumiIndexPage(
          key: asT<Key?>(
            safeArguments['key'],
          ),
        ),
      );
    case '/moreReviews':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => MoreReviewsPage(
          key: asT<Key?>(
            safeArguments['key'],
          ),
          reviewModel: asT<ReviewModel>(
            safeArguments['reviewModel'],
          )!,
          bangumiThemeColor: asT<Color?>(
            safeArguments['bangumiThemeColor'],
          ),
          title: asT<String?>(
            safeArguments['title'],
          ),
        ),
      );
    case '/moreTopics':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => MoreTopicsPage(
          key: asT<Key?>(
            safeArguments['key'],
          ),
          topicModel: asT<TopicModel>(
            safeArguments['topicModel'],
          )!,
          bangumiThemeColor: asT<Color?>(
            safeArguments['bangumiThemeColor'],
          ),
          title: asT<String?>(
            safeArguments['title'],
          ),
        ),
      );
    case '/photoView':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => BangumiPictureViewPage(
          key: asT<Key?>(
            safeArguments['key'],
          ),
          imageProvider: asT<ImageProvider>(
            safeArguments['imageProvider'],
          )!,
        ),
      );
    case '/sendComment':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => SendCommentPage(
          key: asT<Key?>(
            safeArguments['key'],
          ),
          contentID: asT<int?>(
            safeArguments['contentID'],
          ),
          title: asT<String?>(
            safeArguments['title'],
          ),
          postCommentType: asT<PostCommentType?>(
            safeArguments['postCommentType'],
          ),
          referenceObject: asT<String?>(
            safeArguments['referenceObject'],
          ),
          preservationContent: asT<String?>(
            safeArguments['preservationContent'],
          ),
        ),
      );
    case '/subjectComment':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => BangumiCommentPage(
          key: asT<Key?>(
            safeArguments['key'],
          ),
          commentModel: asT<CommentModel>(
            safeArguments['commentModel'],
          )!,
          subjectID: asT<int>(
            safeArguments['subjectID'],
          )!,
          bangumiThemeColor: asT<Color?>(
            safeArguments['bangumiThemeColor'],
          ),
          name: asT<String?>(
            safeArguments['name'],
          ),
        ),
      );
    case '/subjectDetail':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => BangumiDetailPage(
          key: asT<Key?>(
            safeArguments['key'],
          ),
          subjectID: asT<int>(
            safeArguments['subjectID'],
          )!,
        ),
      );
    case '/subjectEp':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => BangumiEpPage(
          key: asT<Key?>(
            safeArguments['key'],
          ),
          epModel: asT<EpModel>(
            safeArguments['epModel'],
          )!,
          totalEps: asT<int>(
            safeArguments['totalEps'],
          )!,
          bangumiThemeColor: asT<Color?>(
            safeArguments['bangumiThemeColor'],
          ),
        ),
      );
    case '/subjectTopic':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => BangumiTopicPage(
          key: asT<Key?>(
            safeArguments['key'],
          ),
          topicModel: asT<TopicModel>(
            safeArguments['topicModel'],
          )!,
          topicInfo: asT<TopicInfo>(
            safeArguments['topicInfo'],
          )!,
          themeColor: asT<Color?>(
            safeArguments['themeColor'],
          ),
        ),
      );
    case '/webview':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => BangumiWebviewPage(
          key: asT<Key?>(
            safeArguments['key'],
          ),
          url: asT<String>(
            safeArguments['url'],
          )!,
          title: asT<String?>(
            safeArguments['title'],
          ),
          targetUrl: asT<String?>(
            safeArguments['targetUrl'],
          ),
          onTargetUrlReached: asT<Function(String?)?>(
            safeArguments['onTargetUrlReached'],
          ),
        ),
      );
    case 'about':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => AboutPage(
          key: asT<Key?>(
            safeArguments['key'],
          ),
        ),
      );
    case 'settings':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => SettingsPage(
          key: asT<Key?>(
            safeArguments['key'],
          ),
        ),
      );
    case 'userPage':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => BanumiUserPage(
          key: asT<Key?>(
            safeArguments['key'],
          ),
        ),
      );
    default:
      return FFRouteSettings(
        name: FFRoute.notFoundName,
        routeName: FFRoute.notFoundRouteName,
        builder: notFoundPageBuilder ?? () => Container(),
      );
  }
}
