// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// **************************************************************************
// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import,unnecessary_import,unused_shown_name,implementation_imports,duplicate_import
import 'package:bangu_lite/models/providers/ep_model.dart';
import 'package:ff_annotation_route_library/ff_annotation_route_library.dart';
import 'package:flutter/widgets.dart';

import '../catalogs/bangumi_detail_page.dart';
import '../catalogs/bangumi_ep_page.dart';
import '../catalogs/bangumi_index_page.dart';
import '../catalogs/more_comments_page.dart';

/// Get route settings base on route name, auto generated by https://github.com/fluttercandies/ff_annotation_route
FFRouteSettings getRouteSettings({
  required String name,
  Map<String, dynamic>? arguments,
  PageBuilder? notFoundPageBuilder,
}) {
  final Map<String, dynamic> safeArguments =
      arguments ?? const <String, dynamic>{};
  switch (name) {
    case '/index':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => BangumiIndexPage(
          key: asT<Key?>(
            safeArguments['key'],
          ),
        ),
      );
    case '/moreComment':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => MoreCommentsPage(
          key: asT<Key?>(
            safeArguments['key'],
          ),
          subjectID: asT<int>(
            safeArguments['subjectID'],
          )!,
          name: asT<String?>(
            safeArguments['name'],
          ),
        ),
      );
    case '/subjectDetail':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => BangumiDetailPage(
          key: asT<Key?>(
            safeArguments['key'],
          ),
          bangumiID: asT<int>(
            safeArguments['bangumiID'],
          )!,
        ),
      );
    case '/subjectEp':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        builder: () => BangumiEpPage(
          key: asT<Key?>(
            safeArguments['key'],
          ),
          epModel: asT<EpModel>(
            safeArguments['epModel'],
          )!,
          totalEps: asT<int>(
            safeArguments['totalEps'],
          )!,
        ),
      );
    default:
      return FFRouteSettings(
        name: FFRoute.notFoundName,
        routeName: FFRoute.notFoundRouteName,
        builder: notFoundPageBuilder ?? () => Container(),
      );
  }
}
