/// Flutter icons MyFlutterApp
/// Copyright (C) 2026 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
library;

import 'package:flutter/widgets.dart';

class MdiExtendsionIcons {
  MdiExtendsionIcons._();

  static const _kFontFam = 'MDIExtendsionIcons';
  static const String? _kFontPkg = null;

  static const IconData calendarImport = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData web = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accountPlusOutline = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accountCircleOutline = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
