// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:bangu_lite/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppConfigAdapter());
    registerAdapter(AppThemeColorAdapter());
    registerAdapter(BangumiSurfTimelineTypeAdapter());
    registerAdapter(ColorAdapter());
    registerAdapter(CommentDetailsAdapter());
    registerAdapter(LoginedUserInformationsAdapter());
    registerAdapter(ScaleTypeAdapter());
    registerAdapter(StarBangumiDetailsAdapter());
    registerAdapter(StarTypeAdapter());
    registerAdapter(SurfTimelineDetailsAdapter());
    registerAdapter(ThemeModeAdapter());
    registerAdapter(UserInformationAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppConfigAdapter());
    registerAdapter(AppThemeColorAdapter());
    registerAdapter(BangumiSurfTimelineTypeAdapter());
    registerAdapter(ColorAdapter());
    registerAdapter(CommentDetailsAdapter());
    registerAdapter(LoginedUserInformationsAdapter());
    registerAdapter(ScaleTypeAdapter());
    registerAdapter(StarBangumiDetailsAdapter());
    registerAdapter(StarTypeAdapter());
    registerAdapter(SurfTimelineDetailsAdapter());
    registerAdapter(ThemeModeAdapter());
    registerAdapter(UserInformationAdapter());
  }
}
